# base configurations
dist: xenial
language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

# no submodules
git:
  submodules: false

# command to install dependencies
install:
  - pip install pipenv
  - pipenv install --dev

# command to run tests
script:
  - coverage run share/test.py

# coverage
after_success:
  - codecov
